// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXqcw6kg-KFxIcYXwOo9CwpPDNIc9uPHQ',
    appId: '1:732986460339:web:0e585ca83832a343a048c6',
    messagingSenderId: '732986460339',
    projectId: 'todoapp-f0b59',
    authDomain: 'todoapp-f0b59.firebaseapp.com',
    storageBucket: 'todoapp-f0b59.firebasestorage.app',
    measurementId: 'G-JJVRG6YPHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbPGZ9sLVsTCIQ8N9LjNhiUQaCOl2zKxE',
    appId: '1:732986460339:android:73774d562973e9fea048c6',
    messagingSenderId: '732986460339',
    projectId: 'todoapp-f0b59',
    storageBucket: 'todoapp-f0b59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNs3qbVDGxXfIY_7HskA8LpLuMNb1-hsw',
    appId: '1:732986460339:ios:559334fc4f039ba2a048c6',
    messagingSenderId: '732986460339',
    projectId: 'todoapp-f0b59',
    storageBucket: 'todoapp-f0b59.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNs3qbVDGxXfIY_7HskA8LpLuMNb1-hsw',
    appId: '1:732986460339:ios:559334fc4f039ba2a048c6',
    messagingSenderId: '732986460339',
    projectId: 'todoapp-f0b59',
    storageBucket: 'todoapp-f0b59.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXqcw6kg-KFxIcYXwOo9CwpPDNIc9uPHQ',
    appId: '1:732986460339:web:5e4396c23375982ca048c6',
    messagingSenderId: '732986460339',
    projectId: 'todoapp-f0b59',
    authDomain: 'todoapp-f0b59.firebaseapp.com',
    storageBucket: 'todoapp-f0b59.firebasestorage.app',
    measurementId: 'G-1L6B698N9C',
  );

}